// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RockRoute.Models;

#nullable disable

namespace RockRouteAPI.Migrations
{
    [DbContext(typeof(ClimbsDB))]
    [Migration("20250225121429_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RockRoute.Models.Climb", b =>
                {
                    b.Property<string>("RouteId")
                        .HasColumnType("text");

                    b.Property<string>("LocationDesciption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<ValueTuple<float, float>>("ParentLocation")
                        .HasColumnType("record");

                    b.Property<string>("ParentSector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProtectionNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SectorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserRatings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YDS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RouteId");

                    b.ToTable("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
